added smoth scroll
infoshareacademy/jfdzl1-red-coders pull request #13
Opened 2017-10-01 16:52 UTC by HKrzyszczak

2017-10-01 20:19 UTC, marcindomanski1 commented on js/animations.js
> +            $('body').animate({
The smooth scroll works for me only after that line is modified to:
`$('html, body').animate({`

2017-10-01 21:07 UTC, marcindomanski1 requested changes
4 issues need to be addressed. The details are included in my comments.

2017-10-01 21:07 UTC, marcindomanski1 commented on index.html
> +                        <li><a class="nav__link" href="#sct3">Stay connected</a></li>
Class "nav__link" changed the 'display' value from 'inline' to 'block'.

2017-10-01 21:07 UTC, marcindomanski1 commented on index.html
> +                    <a href="http://www.redcoders.pl" target="_blank" class="nav__link">
It stopped redirecting to redcoders.pl

2017-10-01 21:07 UTC, marcindomanski1 commented on index.html
> +                            <li><a class="btn nav__link btn--rounded internal" href="#sct1">About app</a></li>
I do not see any use for that new class at this point.

2017-10-02 08:01 UTC, HKrzyszczak commented
Now should be ok. Please review once again.

2017-10-02 17:37 UTC, marcindomanski1 approved these changes

2017-10-02 18:02 UTC, merged