Description section of the lp reformated along GoodPractice lines - I kindly ask for review
infoshareacademy/jfdzl1-red-coders pull request #8
Opened 2017-09-17 10:15 UTC by maciekpollub

2017-09-17 10:21 UTC, HKrzyszczak submitted a review, later dismissed

2017-09-17 11:31 UTC, maciekpollub commented
I kindly ask for the review of the js code.

2017-09-17 11:58 UTC, jakubfedyk requested changes
i think you dont need bracket after if

2017-10-01 16:50 UTC, HKrzyszczak approved these changes

2017-10-08 20:31 UTC, closed without merging